### ISSUE TITLE
Error in get_parsivel2 (line 21)

### ISSUE THREAD

**Issue by raffyjef** [JValdivia23/parsivel2#1]
I am trying to read a .txt file from an OTT Parsivel Disdrometer using the get_parsivel2 function. I am having this error:

Error in get_parsivel2 (line 21)
time=datevec(filename(fdot-13:fdot),'yyyymmddHHMMSS');

Error in parsivel (line 2)
data=get_parsivel2(filename)

Here is my code:
filename='.\20180509091400_ATM4.txt';
data=get_parsivel2(filename)

And attached is the file that I am trying to read
[20180509091400_ATM4.txt](https://github.com/JValdivia23/parsivel2/files/8712465/20180509091400_ATM4.txt)

**Comment by JValdivia23** [comment]
Our files have a header and your file not. To solve this problem in the script just comment or delete the line 17 in "get_parsivel2": %h = textscan(fileID,'%s',2);

**Comment by raffyjef** [comment]
I tried deleting line 17 but this error still persists. Is it possible to request a copy of your sample raw data of the parsivel2 used in your example? thank you

**Comment by JValdivia23** [comment]
Here you have one of our files:
[0000000001_20210914205500.txt](https://github.com/JValdivia23/parsivel2/files/9103956/0000000001_20210914205500.txt)

**Comment by raffyjef** [comment]
Hi! I tried using your file but I still get this error:

Array indices must be positive integers or logical values.

Error in get_parsivel2 (line 21)
time=datevec(filename(fdot-13:fdot),'yyyymmddHHMMSS');

Error in sample (line 2)
data=get_parsivel2(filename)

**Comment by raffyjef** [comment]
On line 21, I tried using time=datevec(filename,'yyyymmddHHMMSS'); and it worked! Thank you very much!
